name = "POFNIR Pack"
author = "MoonCaos & Claude"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3053ad6a9dd84578a731248d77d757519a852e7135c7972ba029289a5766d8c3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
