name = "POFNIR Pack"
author = "MoonCaos & Claude"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c619326ca5bed32ffff7097a92d9ed37aabb77dc664250458fab910783d0ed6c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
