name = "POFNIR Pack"
author = "MoonCaos & Claude"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e73ad281fabe8eabbdf37cf2b127124419b4c2551293fe572eb2de079959ac8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
